/**
 * Dimension Reason Codes — stable enums for ledger/replay/calibration
 *
 * These codes must never change meaning between versions.
 * Adding new codes is safe; renaming/removing is a breaking change.
 */

export const COVERAGE_REASON_CODES = {
  COVERAGE_FULL:                        'COVERAGE_FULL',
  COVERAGE_PARTIAL_SCOPE:               'COVERAGE_PARTIAL_SCOPE',
  COVERAGE_SIGNIFICANT_GAP:             'COVERAGE_SIGNIFICANT_GAP',
  COVERAGE_REQUIRED_EVIDENCE_MISSING:   'COVERAGE_REQUIRED_EVIDENCE_MISSING',
  COVERAGE_NO_SCOPE_MATCHED:            'COVERAGE_NO_SCOPE_MATCHED',
  COVERAGE_SCOPE_COUNT_UNKNOWN:         'COVERAGE_SCOPE_COUNT_UNKNOWN',
  COVERAGE_ALL_MANDATORY_MISSING:       'COVERAGE_ALL_MANDATORY_MISSING',
} as const;

export const FRESHNESS_DIMENSION_REASON_CODES = {
  FRESHNESS_INPUTS_UNAVAILABLE:         'FRESHNESS_INPUTS_UNAVAILABLE',
  FRESHNESS_INDEX_FRESH:                'FRESHNESS_INDEX_FRESH',
  FRESHNESS_STALE_UNRELATED:            'FRESHNESS_STALE_UNRELATED',
  FRESHNESS_SCOPE_STALE:                'FRESHNESS_SCOPE_STALE',
} as const;

export const MAPPING_REASON_CODES = {
  MAPPING_CLEAN_SINGLE_TARGET:          'MAPPING_CLEAN_SINGLE_TARGET',
  MAPPING_CHAIN_TARGET:                 'MAPPING_CHAIN_TARGET',
  MAPPING_SCATTER_DETECTED:             'MAPPING_SCATTER_DETECTED',
  MAPPING_PRIMARY_TARGET_AMBIGUOUS:     'MAPPING_PRIMARY_TARGET_AMBIGUOUS',
  MAPPING_SCATTERED:                    'MAPPING_SCATTERED',
  MAPPING_NO_PRIMARY_TARGET:            'MAPPING_NO_PRIMARY_TARGET',
  MAPPING_PATTERN_UNKNOWN:              'MAPPING_PATTERN_UNKNOWN',
} as const;

export const CONFLICT_REASON_CODES = {
  CONFLICT_NONE:                        'CONFLICT_NONE',
  CONFLICT_ADVISORY:                    'CONFLICT_ADVISORY',
  CONFLICT_HIGH_SEVERITY:               'CONFLICT_HIGH_SEVERITY',
  CONFLICT_BLOCKING:                    'CONFLICT_BLOCKING',
} as const;

export const GRAPH_REASON_CODES = {
  GRAPH_COMPLETE:                       'GRAPH_COMPLETE',
  GRAPH_SCOPE_PARSE_FAILURE:            'GRAPH_SCOPE_PARSE_FAILURE',
  GRAPH_SYMBOL_RESOLUTION_DEGRADED:     'GRAPH_SYMBOL_RESOLUTION_DEGRADED',
  GRAPH_DEPTH_TRUNCATED:                'GRAPH_DEPTH_TRUNCATED',
  GRAPH_FALLBACK_HIGH:                  'GRAPH_FALLBACK_HIGH',
  GRAPH_CRITICAL_NODES_MISSING:         'GRAPH_CRITICAL_NODES_MISSING',
  GRAPH_SYMBOL_RESOLUTION_UNKNOWN:      'GRAPH_SYMBOL_RESOLUTION_UNKNOWN',
} as const;

export const MAPPING_QUALITY_REASON_CODES = {
  /** Mapping dimension was scored using the quantitative 4-sub-metric engine (Sprint 14+). */
  MAPPING_QUALITY_SCORED:               'MAPPING_QUALITY_SCORED',
  /** Hard-block condition triggered — no safe execution target can be identified. */
  MAPPING_QUALITY_HARD_BLOCK:           'MAPPING_QUALITY_HARD_BLOCK',
} as const;
